pipeline:
  scp:
    image: appleboy/drone-scp
    pull: true
    host:
      - 139.162.9.68
    port: 22  
    username: root
    user: root
    secrets: [ ssh_password ]
    target: /root
    source:
      - /drone/src/github.com/reactgrils/stream-api-server
    when:
      branch: master
  ssh:
    image: appleboy/drone-ssh
    host: 
      - 139.162.9.68
    username: root
    user: root
    secrets: [ ssh_password ]
    command_timeout: 600
    script:
      - . /root/.nvm/nvm.sh && nvm use 10.9.0
      - mkdir -p /var/www/html/stream-api-server.tomas.website
      - cp -a /root/drone/src/github.com/reactgrils/stream-api-server/* /var/www/html/stream-api-server.tomas.website/
      - cd /var/www/html/stream-api-server.tomas.website
      - yarn install
      - cp /root/stream-api-server.config /var/www/html/stream-api-server.tomas.website/.env
      - rm -rf /root/drone
    when:
      branch: master
